### ISSUE TITLE
grbl-panel does not connect to ramps1.4

### ISSUE THREAD

**Issue by skeitzer1** [gerritv/Grbl-Panel#21]
I found I needed to add a sleep(1000) between the set dtr and clear dtr which is used to reset the arduino.

This cleared my hang on connect. The arduino needs time to completely reset before any commands are issued to it..

Nice program..  using it to control my Shapeoko 2

Thanks

**Comment by gerritv** [comment]
Interesting, is that over and above the Start up Delay that is configurable on the Settings page?

Someone else had reported a problem with Mega2560, which is why I added that setting.

**Comment by electrokean** [comment]
I was having the same issue this weekend using Grbl-Panel with a Mega2560 (running a custom 6-axis version of Grbl I'm testing out).
If I monitor the serial data, I can see the "?" status enquiries start immediately, rather than waiting based on the start up delay.
The fix was be pretty simple:  In GrblGui.vb subroutine btnConnDisconnect_Click, move the line "statusPrompt("Start")" one line down so it is after the Sleep().
After I did this, I had no problems connecting.

**Comment by electrokean** [comment]
It is a trivial change, but I've created a pull request

**Comment by gerritv** [comment]
Finally integrating this into a release. Should be done before Nov 10

**Comment by gerritv** [comment]
Fixed in Release 1.0.5.0
Thank you for your patience
